apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

# This give our HPA a name.
metadata:
  name: devconnect-backend-hpa

# spec means What do we want this HPA to do?
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devconnect-backend

  minReplicas: 2
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70