apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: devconnect-backend-pvc

spec:
  accessModes:
    - ReadWriteOnce
# means the volume can be mounted read/write by a single node.
  resources:
    requests:
      storage: 1Gi
      # I need 1 GB of persistent storage